# Generated by Django 4.0 on 2021-12-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='prise',
            new_name='price',
        ),
    ]
