# Generated by Django 3.2.8 on 2021-12-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True, verbose_name='Трейлер'),
        ),
    ]
